apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: text-editor/server
        name: server
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 10
        envFrom:
          - secretRef:
              name: server-env
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "300Mi"
            cpu: "1"
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
