apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: text-editor
commonLabels:
  project: text-editor-server
resources:
- ./deployment.yaml
- ./lb.service.yaml
#- ./service.yaml # Remove since GKE Ingress is buggy
