apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: server
